### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stalxed** [akeneo/BatchBundle#56]
I've created a topic on the forum http://www.akeneo.com/forums/topic/how-to-use-akeneobatchbundle/#post-3861
With this bundle is very difficult to get started.
Bundle perform complex actions. Without documentation generally start working with it is practically impossible.
Please add at least some simple documentation that at least it was possible to start working with the bundle.

**Comment by nidup** [comment]
Hello, 

Thank you for your feedback.

FYI, we have a documentation for the Akeneo PIM BaseConnectorBundle, this bundle uses the BatchBundle, it already gives some hints see http://docs.akeneo.com/master/cookbook/import_export/index.html

The architecture is inspired by Spring Batch, see http://docs.spring.io/spring-batch/reference/html/domain.html for an explanation of the Domain Language objects you will find in this BatchBundle.
