### ISSUE TITLE
Wrong parameter in service

### ISSUE THREAD

**Issue by matooma** [akeneo/BatchBundle#84]
There is a dependency on a non existing parameter in the service.yml:

PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException' with message 'The service "akeneo_batch.job_instance_factory" has a dependency on a non-existent parameter "akeneo_batch.entity.job_instance.class". Did you mean this: "akeneo_batch.entity.job_execution.class"?' in /home/dev04/projects/universe/prod/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:108

**Comment by ste93cry** [comment]
:+1: same problem here with Symfony 2.7.9 and BatchBundle 0.4. Could this be fixed and a new version released?

**Comment by nidup** [comment]
Sorry for the very late answer, it has been fixed in 0.4.2
