### ISSUE TITLE
Issue with akeneo_batch_job_execution getting to big

### ISSUE THREAD

**Issue by oliverde8** [akeneo/BatchBundle#85]
Hi, 

We are using akeneo_batch on our project to import products (as expected XD). It has been running fine for a few month now but recently we started having issues on one of our batch. The batch is configured to be launched every 5 minutes in the cron tab. 

The issue is the bundle does a Select query in akeneo_batch_job_execution table and it crashes on it because that job instance has over 50k executions in the table. 

I am not sure why it does this select, we are considering deleting all the lines in the table for now but we also need a long term solution. 

We are using version 0.3.5 of the bundle. I hope it is already; :smile:  fixed but couldn't find anything about it. 

Thanks

**Comment by nidup** [comment]
Hi!
Sorry for the very late answer, it has been fixed in 0.3.8 (also fied on more recent versions), cf https://github.com/akeneo/BatchBundle/commit/f12784d4b3fbb37b8bbc4794aec1a26bb865077c
